# Generated by Django 5.1 on 2024-08-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(choices=[('RN', 'Pau dos Ferros'), ('RN', 'São Miguel'), ('RN', 'Alexandria'), ('RN', 'Tenente Ananias'), ('CE', 'Pereiro')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('curso', models.CharField(choices=[('CS', 'Ciência da Computação'), ('ENG', 'Engenharia'), ('MED', 'Medicina'), ('ENF', 'Enfermagem')], max_length=3)),
            ],
        ),
    ]
